INSERT INTO restaurant (name, address, category) VALUES ('Chilis Grill & Bar', '2425 Katy Fwy', 'American');
INSERT INTO restaurant (name, address, category) VALUES ('MKT Bar', '1001 Austin St', 'American');
INSERT INTO restaurant (name, address, category) VALUES ('Merida Mexican Restaurant', '2509 Navigation Blvd', 'Tex-Mex');
INSERT INTO restaurant (name, address, category) VALUES ('Rudys', '3600 I-45', 'BBQ');
INSERT INTO restaurant (name, address, category) VALUES ('Carlitos', '600 Spanish Way', 'Tex-Mex');
INSERT INTO restaurant (name, address, category) VALUES ('The Olive Garden', '1200 W Sam Houston PKWY', 'Italian');
INSERT INTO restaurant (name, address, category) VALUES ('Pizza Hut', '3402 Airport Blvd', 'Pizza');
INSERT INTO restaurant (name, address, category) VALUES ('Jack in the Box', '2400 Louetta Rd', 'Fast Food');
INSERT INTO restaurant (name, address, category) VALUES ('Sloppy Joes', '1234 Street', 'American');
INSERT INTO restaurant (name, address, category) VALUES ('Jack in the Box', '2400 Louetta Rd', 'Fast Food');
INSERT INTO restaurant (name, address, category) VALUES ('Hamburger Hut', 'La Grange Blvd', 'American');
INSERT INTO restaurant (name, address, category) VALUES ('Little Italy', '8300 Sicilian Dr', 'Italian');
